baseURL = 'https://ansel.photos/'
defaultContentLanguage = 'en'
copyright = '© Copyright 2022-2024 – Aurélien Pierre'
title = 'Ansel'
theme = 'ansel'

enableGitInfo = true
defaultContentLanguageInSubdir = true
canonifyURLs = true
removePathAccents = true
timeout = "360s"


[author]
  name = 'Aurélien Pierre'
  GitHubUser = 'aurelienpierre'
  url = "https://aurelienpierre.com"

[menu]
  [[menu.main]]
    identifier = "workflows"
    name = "Workflows"
    url = "/workflows/"
    weight = 3
    parent = "learn"


  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 1

  [[menu.main]]
    identifier = "learn"
    name = "Learn"
    url = "#"
    weight = 2

  [[menu.main]]
    identifier = "support"
    name = "Support"
    url = "/support/"
    weight = 7

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 6
    parent = "learn"

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/doc/"
    weight = 3
    parent = "learn"

  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "https://community.ansel.photos/"
    weight = 5

  [[menu.main]]
    identifier = "contributors"
    name = "Contribute"
    url = "contribute"
    weight = 8

[languages]
  [languages.en]
    title = 'Ansel'
    languagename = "English"
    weight = 1
  [languages.fr]
    title = 'Ansel'
    languagename = "Français"
    weight = 2
  [languages.de]
    title = 'Ansel'
    languagename = "Deutsch"
    weight = 3
  [languages.eo]
    title = 'Ansel'
    languageName = "Esperanto"
    weight = 5
  [languages.es]
    title = 'Ansel'
    languagename = "Español"
    weight = 6
  [languages.gl]
    title = 'Ansel'
    languagename = "Galician"
    weight = 7
  [languages.it]
    title = 'Ansel'
    languagename = "Italian"
    weight = 8
  [languages.pl]
    title = 'Ansel'
    languagename = "Polish"
    weight = 9
  [languages.pt_br]
    title = 'Ansel'
    languagename = "Português"
    weight = 10
  [languages.uk]
    title = 'Ansel'
    languagename = "Ukrainian"
    weight = 11
  [languages.nl]
    title = 'Ansel'
    languagename = "Dutch"
    weight = 12
  [languages.ja]
    title = 'Ansel'
    languagename = "Japanese"
    weight = 13


[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = true

  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    tabWidth = 4

FootnoteReturnLinkContents = "↩"

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/aurelienpierreeng/ansel-doc"

    # Get translations and auto-gen tools
    [[module.imports.mounts]]
      source = 'tools'
      target = 'content/doc/tools'

    [[module.imports.mounts]]
      source = 'po'
      target = 'content/doc/po'

    [[module.imports.mounts]]
      source = 'content/'
      target = 'content/doc/'
      lang= "en"

    [[module.imports.mounts]]
      source = '_gen/fr/content/'
      target = 'content/doc/'
      lang= "fr"

    [[module.imports.mounts]]
      source = '_gen/de/content/'
      target = 'content/doc/'
      lang= "de"

    [[module.imports.mounts]]
      source = '_gen/eo/content/'
      target = 'content/doc/'
      lang= "eo"

    [[module.imports.mounts]]
      source = '_gen/uk/content/'
      target = 'content/doc/'
      lang= "uk"

    [[module.imports.mounts]]
      source = '_gen/es/content/'
      target = 'content/doc/'
      lang= "es"

    [[module.imports.mounts]]
      source = '_gen/gl/content/'
      target = 'content/doc/'
      lang= "gl"

    [[module.imports.mounts]]
      source = '_gen/pt_br/content/'
      target = 'content/doc/'
      lang= "pt_br"

    [[module.imports.mounts]]
      source = '_gen/it/content/'
      target = 'content/doc/'
      lang= "it"

    [[module.imports.mounts]]
      source = '_gen/pl/content/'
      target = 'content/doc/'
      lang= "pl"

    [[module.imports.mounts]]
      source = '_gen/nl/content/'
      target = 'content/doc/'
      lang= "nl"

    [[module.imports.mounts]]
      source = '_gen/ja/content/'
      target = 'content/doc/'
      lang= "ja"

  # Deal with partially-translated sections
  [[module.mounts]]
    source = 'content/contribute/'
    target = 'content/contribute/'
    lang= "fr"

  [[module.mounts]]
    source = 'content/news/'
    target = 'content/news/'
    lang= "fr"

  [[module.mounts]]
    source = 'content/workflows/'
    target = 'content/workflows/'
    lang= "fr"

  [[module.mounts]]
    source = 'content/resources/'
    target = 'content/resources/'
    lang= "fr"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[taxonomies]
  tag = "tags"
	author = "authors"

[imaging]
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 86
  resampleFilter = 'linear'

[Params.Images]
    maxSize = 4096
    setSizes = [ 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, 2200, 2400, 2600, 2800, 3000 ]
    sizes = "(max-width: 992px) 100vw, (max-width: 1200px) 66.67vw, 50vw"

[related]
  includeNewer = true
  threshold = 20
  toLower = true
  [[related.indices]]
      applyFilter = false
      cardinalityThreshold = 0
      name = 'keywords'
      pattern = ''
      toLower = false
      type = 'basic'
      weight = 100
  [[related.indices]]
      applyFilter = false
      cardinalityThreshold = 0
      name = 'categories'
      pattern = ''
      toLower = false
      type = 'basic'
      weight = 100
  [[related.indices]]
      applyFilter = false
      cardinalityThreshold = 0
      name = 'date'
      pattern = ''
      toLower = false
      type = 'basic'
      weight = 10
  [[related.indices]]
      applyFilter = false
      cardinalityThreshold = 0
      name = 'tags'
      pattern = ''
      toLower = false
      type = 'basic'
      weight = 80
  [[related.indices]]
      applyFilter = false
      cardinalityThreshold = 0
      name = 'content'
      pattern = ''
      toLower = false
      type = 'basic'
      weight = 80
